# Configuration:
# 
# disabled
#   false if tracking tag should be shown
# use_async
#   Set to true if you want to use asynchronous tracking
# url
#   The url of your piwik instance (e.g. webstats.library.cornell.edu/piwik/
# id_site
#   The id of your website inside Piwik
#
production:
  piwik:
    id_site: 2
    url: webstats.library.cornell.edu
    use_async: true
    disabled: false

development:
  piwik:
    id_site: 2
    url: webstats.library.cornell.edu
    disabled: true
    use_async: false
    hostname: localhost

test:
  piwik:
    id_site: 2
    url: webstats.library.cornell.edu
    disabled: true
    use_async: false
    hostname: localhost 

integration:
  piwik:
    id_site: 2
    url: webstats.library.cornell.edu
    disabled: true
    use_async: false
    hostname:  localhost

staging:
  piwik:
    id_site: 2
    url: webstats.library.cornell.edu
    disabled: true
    use_async: false
    hostname:  localhost
